kind: helm-release
apiVersion: 1.1
build:
  context: .
  dockerfile: Dockerfile
install:
  chart: charts/audio-analyzer
  values:
  - values.dev.yaml?
  - secrets.dev.yaml?
  set:
    replicaCount: 1
    image:
      repository: audio-analyzer
      tag: $(tag)
      pullPolicy: Never
    ingress:
      annotations:
        kubernetes.io/ingress.class: traefik-azds
      hosts:
      # This expands to form the service's public URL: [space.s.][rootSpace.]audio-analyzer.<random suffix>.<region>.azds.io
      # Customize the public URL by changing the 'audio-analyzer' text between the $(rootSpacePrefix) and $(hostSuffix) tokens
      # For more information see https://aka.ms/devspaces/routing
      - $(spacePrefix)$(rootSpacePrefix)audio-analyzer$(hostSuffix)
configurations:
  develop:
    build:
      useGitIgnore: true
    container:
      sync:
      - "!**/package.json"
      iterate:
        processesToKill: [node]